FROM louislam/uptime-kuma:base-debian
WORKDIR /app

# Copy app files from build layer
COPY . .

RUN npm ci --legacy-peer-deps && npm run build && chmod +x /app/extra/entrypoint.sh

EXPOSE 3001
VOLUME ["/app/data"]
HEALTHCHECK --interval=60s --timeout=30s --start-period=180s --retries=5 CMD node extra/healthcheck.js
ENTRYPOINT ["/usr/bin/dumb-init", "--", "extra/entrypoint.sh"]
CMD ["node", "server/server.js"]
