kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-pqe
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-subdir-external-provisioner
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
